<?php
/**
 * Created by PhpStorm.
 * User: Mouncef
 * Date: 25/06/2017
 * Time: 16:50
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticlenewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlenewsRepository extends EntityRepository
{
    public function findNbEnregistrement(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(n.id) FROM AppBundle:Articlenews n'
            )
            ->getSingleScalarResult();
    }

    public function findLatestPublishedArticles(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT n FROM AppBundle:Articlenews n WHERE n.isPublished = 1 ORDER BY n.date DESC'
            )
            ->getResult()
            ;
    }

    public function find5LatestPublishedArticles(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT n FROM AppBundle:Articlenews n WHERE n.isPublished = 1 ORDER BY n.date DESC'
            )
            ->setMaxResults(5)
            ->getResult()
            ;
    }

    public function findLastPublishedArticle(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT n FROM AppBundle:Articlenews n WHERE n.isPublished = 1 ORDER BY n.date DESC'
            )
            ->setMaxResults(1)
            ->getOneOrNullResult()
            ;
    }

}