<?php
/**
 * Created by PhpStorm.
 * User: Mouncef
 * Date: 21/06/2017
 * Time: 18:04
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticlekitchenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlekitchenRepository extends EntityRepository
{
    public function findNbEnregistrement(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(k.id) FROM AppBundle:Articlekitchen k'
            )
            ->getSingleScalarResult();
    }

    public function findLatestPublishedArticles(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT k FROM AppBundle:Articlekitchen k WHERE k.isPublished = 1 ORDER BY k.date DESC'
            )
            ->getResult()
            ;
    }

    public function find5LatestPublishedArticles(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT k FROM AppBundle:Articlekitchen k WHERE k.isPublished = 1 ORDER BY k.date DESC'
            )
            ->setMaxResults(5)
            ->getResult()
            ;
    }

    public function findLastPublishedArticle(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT k FROM AppBundle:Articlekitchen k WHERE k.isPublished = 1 ORDER BY k.date DESC'
            )
            ->setMaxResults(1)
            ->getOneOrNullResult()
            ;
    }
}