<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Articlemode;
use Doctrine\ORM\EntityRepository;

/**
 * ArticlemodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlemodeRepository extends EntityRepository
{
    public function findNbEnregistrement(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(m.id) FROM AppBundle:Articlemode m'
            )
            ->getSingleScalarResult();
    }

    public function findLatestPublishedArticles(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT m FROM AppBundle:Articlemode m WHERE m.isPublished = 1 ORDER BY m.date DESC'
            )
            ->getResult()
            ;
    }

    public function find5LatestPublishedArticles(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT m FROM AppBundle:Articlemode m WHERE m.isPublished = 1 ORDER BY m.date DESC'
            )
            ->setMaxResults(5)
            ->getResult()
            ;
    }

    public function findLastPublishedArticle(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT m FROM AppBundle:Articlemode m WHERE m.isPublished = 1 ORDER BY m.date DESC'
            )
            ->setMaxResults(1)
            ->getOneOrNullResult()
            ;
    }
}
