<?php
/**
 * Created by PhpStorm.
 * User: Mouncef
 * Date: 22/06/2017
 * Time: 17:24
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticlehealthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlehealthRepository extends EntityRepository
{
    public function findNbEnregistrement(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(h.id) FROM AppBundle:Articlehealth h'
            )
            ->getSingleScalarResult();
    }

    public function findLatestPublishedArticles(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT h FROM AppBundle:Articlehealth h WHERE h.isPublished = 1 ORDER BY h.date DESC'
            )
            ->getResult()
            ;
    }

    public function find5LatestPublishedArticles(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT h FROM AppBundle:Articlehealth h WHERE h.isPublished = 1 ORDER BY h.date DESC'
            )
            ->setMaxResults(5)
            ->getResult()
            ;
    }

    public function findLastPublishedArticle(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT h FROM AppBundle:Articlehealth h WHERE h.isPublished = 1 ORDER BY h.date DESC'
            )
            ->setMaxResults(1)
            ->getOneOrNullResult()
            ;
    }
}