<?php

namespace AppBundle\Repository;


use Doctrine\ORM\EntityRepository;

/**
 * ArticlebeautyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlebeautyRepository extends EntityRepository
{
    public function findNbEnregistrement(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(b.id) FROM AppBundle:Articlebeauty b'
            )
            ->getSingleScalarResult();
    }

    public function findLatestPublishedArticles(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT b FROM AppBundle:Articlebeauty b WHERE b.isPublished = 1 ORDER BY b.date DESC'
            )
            ->getResult()
            ;
    }

    public function find5LatestPublishedArticles(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT b FROM AppBundle:Articlebeauty b WHERE b.isPublished = 1 ORDER BY b.date DESC'
            )
            ->setMaxResults(5)
            ->getResult()
            ;
    }

    public function findLastPublishedArticle(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT b FROM AppBundle:Articlebeauty b WHERE b.isPublished = 1 ORDER BY b.date DESC'
            )
            ->setMaxResults(1)
            ->getOneOrNullResult()
            ;
    }


}
