<?php

namespace AppBundle\Repository;

/**
 * CatModeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatBeautyRepository extends \Doctrine\ORM\EntityRepository
{
}
