<?php
/**
 * Created by PhpStorm.
 * User: Mouncef
 * Date: 25/06/2017
 * Time: 16:51
 */

namespace AppBundle\Repository;

/**
 * CatFamilyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatFamilyRepository extends \Doctrine\ORM\EntityRepository
{

}