<?php
/**
 * Created by PhpStorm.
 * User: Mouncef
 * Date: 22/06/2017
 * Time: 17:24
 */

namespace AppBundle\Repository;

/**
 * CatHealthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatHealthRepository extends \Doctrine\ORM\EntityRepository
{

}