<?php
/**
 * Created by PhpStorm.
 * User: Mouncef
 * Date: 21/06/2017
 * Time: 18:00
 */

namespace AppBundle\Repository;

/**
 * CatKitchenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatKitchenRepository extends \Doctrine\ORM\EntityRepository
{

}