<?php
/**
 * Created by PhpStorm.
 * User: Mouncef
 * Date: 10/07/2017
 * Time: 16:22
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * CatStarsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatStarsRepository extends EntityRepository
{

}