<?php

namespace AppBundle\Repository;

/**
 * CatVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatVideoRepository extends \Doctrine\ORM\EntityRepository
{
}
