<?php

namespace AppBundle\Repository;

/**
 * DayAdviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DayAdviceRepository extends \Doctrine\ORM\EntityRepository
{
}
