<?php

namespace AppBundle\Repository;

/**
 * DayPictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DayPictureRepository extends \Doctrine\ORM\EntityRepository
{
}
