<?php

namespace AppBundle\Repository;

/**
 * HoroscopeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HoroscopeRepository extends \Doctrine\ORM\EntityRepository
{
}
