<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventionRepository extends EntityRepository
{
    public function find5LatestPublishedArticles(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT inv FROM AppBundle:Invention inv WHERE inv.isPublished = 1 ORDER BY inv.date DESC'
            )
            ->setMaxResults(5)
            ->getResult()
            ;
    }
}
