<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SondageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SondageRepository extends EntityRepository
{
    public function find5LatestPublishedArticles(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT son FROM AppBundle:Sondage son WHERE son.isPublished = 1 ORDER BY son.date DESC'
            )
            ->setMaxResults(5)
            ->getResult()
            ;
    }
}
